apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: club-backend
  template:
    metadata:
      labels:
        app: club-backend
    spec:
      containers:
        - name: backend
          image: clubholo/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/clubdb
            - name: MONGO_URL
              value: mongodb://mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: club-backend
spec:
  selector:
    app: club-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
